# Generated by Django 4.1 on 2024-12-14 10:35

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=cinema.models.create_custom_path),
        ),
    ]
